minesweeper:
  siteName: Minesweeper-io
  siteAddress: localhost:3000
  config:
    salty:
      password: '@maven.salty.password@'
      activation: '@maven.salty.activation@'
      recover: '@maven.salty.recover@'
    mail:
      smtpHost: @maven.mail.host@
      smtpPort: @maven.mail.port@
      fromMail: ${mail.from}
      user: ${mail.user}
      pass: ${mail.pass}
flyway:
  validateOnMigrate: false
spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: '@maven.db.url@'
    username: '@maven.db.username@'
    password: '@maven.db.password@'
    testWhileIdle: true
    validationQuery: SELECT 1
    platform: postgres
  jackson:
    serialization-inclusion: non_null
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/.well-known/jwks.json